version: "3"

services:
    minecraft-server:
        container_name: ${container_name}
        build:
            context: .
            args:
                RAM_AMOUNT: ${RAM_AMOUNT}
        volumes:
            - /mnt/mine_server_data:/server
        ports:
            - 25565:25565
            - 25575:25575
            - 19132:19132
volumes:
    mine_server_data:



