version: "3"

services:
    minecraft-server:
        container_name: ${container_name}
        build:
            context: .
            args:
                RAM_AMOUNT: ${RAM_AMOUNT}
        volumes:
            - /mnt/modpack_server_data:/server
        ports:
            - 25565:25565
            - 25575:25575
volumes:
    modpack_server_data:



